sudo: false
language: ruby
cache: bundler
rvm:
- 2.7.0

install:
  # Install Jekyll and dependencies
  - bundle install

before_script:
  - git config --global user.email "is2js@naver.com"
  - git config --global user.name "is3js"

script: bundle exec rake site:deploy --quiet #--trace

# Generate your secure token with the travis gem:
# get Github token from your Travis CI profile page
# gem install travis
# GH_TOKEN from https://github.com/settings/tokens
# travis encrypt 'GIT_NAME="YOUR_USERNAME" GIT_EMAIL="YOUR_EMAIL" GH_TOKEN=YOUR_TOKEN'
env:
  global:
    secure: "MdxyzfT2NnQONblWHUpmO623wFHKniN1e/ms1jZx+/yq5cB53aKqO6HrJVVKrhEYnYtqXpr4o6lXIk9yjm27g3o4f2XUST5vTVif6DUa+SYuKAYGsX1ZZOmkpwYlPKNlUAoCCm02KfzcOkUGH5gdiIzhYLFK6Y+nZ4bxwsO8B/2u18AJuc9JDMEUCaAq2BiEkF09XcqmOvgN7369smi+QXnYOME/y0JZ
            YYwXzlHFyQykH7YmO7WR33RbChMJXlSgqH6e3Ko5z6yMD3aVtAJ+2k+h0CttZD3OhRBoYbp9rgFD/3wo/W+MiBoIkpwpq1i+fqsQyB1BF+5vG0Dhetnod5AYpeDj+VQqDyxt32Tiq9HMIIgtHRrwrwjo5t2hjHe0aKtqwmFXXSEvoF5k9SXW995eOUWsYw0hbl+tTATBTIBd8yffz7FbrkvG0QcEqONK11uUCaNUfLh
            p6gYKAKbiZPUUr8SoKuFTREG5hDyDzmQXCgqfwmJgza0S8lILax70xp7xxl3KorMRe0wHiWEWZZKc5UUsqANlMrjj6ePnyJUfXWUaEUj815/lXlE8amyxBWWpSCDDXAJVD7I3Y6jEqk887YJ73puAmTVDCEG6grwnIUCtWiiKPutqm21VwzR7xLyH6VBSAQU7ORN/bpkBS5eROgxX1/iHbSnEEsgGTfI="
branches:
  only:
    - main