language: ruby
cache: bundler
rvm:
- 2.7.0
install:
- bundle install
before_script:
- git config --global user.email "is2js@naver.com"
- git config --global user.name "is3js"
script: bundle exec rake site:deploy --quiet
env:
  global:
  - secure: HXB08hxqyi73HggXrefdkVITHqDGDw7eUX7WD1H+MlzFi/ONDqUexxjapZ19x/8YgvRoDr4j51NcIs6QN3570MVc6PAALYkJUiadgKdxfQPucVxIh0MroSFyQBXnWw2uNtO6Evbfs3TBcBxgbSzLGr4SuucFOrB3qbRMPuHB6MP8sfgy2VVTnI15CFa8WWtl7qgYcA87YkedQrnz8b48rNusajDCnN/dvYZf1agRp3x0FsfQ+eIAFBRDbThx2LFm1ZZBP4UlA1qu9Y9cTmaRtcbDNyULekuLkDh8/A8Tx+32Q1YavSOkzBgwpubPTFNICPLGj9L9okbCM4hH0g1oxeJ1oSh1XKtjs7h6n4vuOUoHjhQAqaN2QSnlNtvwbM2WxnlI2E3Ng26KLf4krtDcZrjUimAcyj1QDDGGHt57qZiOyAVB2gPxHFeheFd+uBFapJtGThgF2HutrpU/rg+qHSENu+Adp3p+L3lXayZJ6eIDQzOZY0Ld2YogmjmpbVPS+4eAvl2N+MroBTMwoF/dANAOD1te6SLnin/G0ZlVaFHuaGlv75AkXzW7dHTKyVRfZrCum0/AxqNLpX68JRFOUnUM+ZL0WYz22Ht3yEna0bqfujH5oCXfGW4EK+0yu/Y3+pm/QiUVYIOkUfEmhgQOT1HsRi+DNc0cd409KQf1y24=
branches:
  only:
  - main
