sudo: false
language: ruby
cache: bundler
rvm:
- 2.7.0
install:
- bundle install
before_script:
- git config --global user.email "is2js@naver.com"
- git config --global user.name "is3js"
script: bundle exec rake site:deploy --quiet
env:
  global:
  - secure: FzOC4loDvW+uJDk3lP8ZdyBsJ88qe6n90CrGiunSpfmQil6DbVgwaoZomTLENA+VUsxA+IhezjZI+lOXdQbItyAnUNnilfCQFUB/g8wLtdHUAV1NTj2f/M1HntjIpVu5l+RCyMB6azEt7o3Q7BEwBgAJyD9oziwsl05fXmdcMd0mxGcAD0/jWRW5eFDLRAlZCrCjQpZljRvrDV90DZBvgoZrvHqiV3OM
      b0EZtw/mz9LkMHdL5iJc6+z7XCPInEhynbbMbZdJWo7LPXBCGtKjStjRKzZ/Pu1UDjoLJb9/17jek2ntz2Qz0XD2OQUAH5RnUjSe1GWO3DJtgCpbgJfPwLl+G4/Q5rgGlerZfbfPkRx0EZ6v3UyoSX0r/qysYRhci4c2mTitwxzSQZMsgMXMja3uBaUHyRgacpDBJ/88gvamhIOsj3fi+ixqmGuhibYXxYkdPh9JSR9
      F595qoJmsKtvi6LAV5jBd99ggl+aMgeahdna1gYIzDhfgLfxvgSSFnJVq9leFLiXzR8iH9x/XqWoGSnZpywoTYVqYAn2t023LqBj+N1WgVMV2Q7Ol5eiiGY+Usr1ob8c6P28ggdhGx0DQOSzatD40D+tNGa/fSBbzH1n10jUkm8+zGsuUbePxmfXsOrleR5/ahX1U5lp4/dbVbiSjWU0jft4Y6A9XJls=
  - secure: d4p2ufnK/2EYg8egY0euGgwrHCQkL55EIyRgg+tUvsJh6sCMA2VUrWDIDhrP44sem97nySzWbQsP1P06fvtbO87u4BrRgLirsb3W/+QfgJsulx2EQyxZ/pWs9NPRZZNVxGJB62fIhWH6Wa0SVx7vAyIoaqGw1h/hp1UNgth/KF/M4nRX93IaYmX0pczhKBZ/eH6RK56Az4ZJNRu6tY24ozEPwH8TlCBQSO2l0gqR3TuFAQzpJfoAJvcmqHwyaGKgOa62u0DASZrDrE6mCePhVSOSoThuOLueRW6QwUO3nOuWHY50cWoFwQgyzG0/+ZwNIrViX9lfYXbwfbl0DFksM2IxfRPHC/6Z8mPnehq8Sy8W1Equ85tdlUNwbKiaHZ8O+1yIpM+t4nkBtiYrxtTJIQgjfqpBlUWZe5UnTIroFciEqpGUpf8jQ4lI0/OahHP0ggUmcuV3vyl2sbk7vnkxQrI2q5T49ZKf6VKsd1dLSRZx7oh1/B5zWDrpRHbkjM2YKELvGB+RepvYIG3F1s+s+9yAWEENwQFrXZED/+biUi+hxDL9/gpyy/NVO1ffFUDnA2PrLzr/IfmHaAQ0HYrRdfuBajwWgJrMwN1F5EcNu6vtfsbwgkns9AI4J0EZifcpyFsdWjXU67udes1ARD2OALHz8vVgqlydvkjbEOjYmp0=
branches:
  only:
  - main
