language: ruby
cache: bundler
rvm:
- 2.7.0
install:
- bundle install
before_script:
- git config --global user.email "is2js@naver.com"
- git config --global user.name "is3js"
script: bundle exec rake site:deploy --quiet
env:
  global:
    secure: "FzOC4loDvW+uJDk3lP8ZdyBsJ88qe6n90CrGiunSpfmQil6DbVgwaoZomTLENA+VUsxA+IhezjZI+lOXdQbItyAnUNnilfCQFUB/g8wLtdHUAV1NTj2f/M1HntjIpVu5l+RCyMB6azEt7o3Q7BEwBgAJyD9oziwsl05fXmdcMd0mxGcAD0/jWRW5eFDLRAlZCrCjQpZljRvrDV90DZBvgoZrvHqiV3OM
            b0EZtw/mz9LkMHdL5iJc6+z7XCPInEhynbbMbZdJWo7LPXBCGtKjStjRKzZ/Pu1UDjoLJb9/17jek2ntz2Qz0XD2OQUAH5RnUjSe1GWO3DJtgCpbgJfPwLl+G4/Q5rgGlerZfbfPkRx0EZ6v3UyoSX0r/qysYRhci4c2mTitwxzSQZMsgMXMja3uBaUHyRgacpDBJ/88gvamhIOsj3fi+ixqmGuhibYXxYkdPh9JSR9
            F595qoJmsKtvi6LAV5jBd99ggl+aMgeahdna1gYIzDhfgLfxvgSSFnJVq9leFLiXzR8iH9x/XqWoGSnZpywoTYVqYAn2t023LqBj+N1WgVMV2Q7Ol5eiiGY+Usr1ob8c6P28ggdhGx0DQOSzatD40D+tNGa/fSBbzH1n10jUkm8+zGsuUbePxmfXsOrleR5/ahX1U5lp4/dbVbiSjWU0jft4Y6A9XJls="
branches:
  only:
  - main
